### ISSUE TITLE
date/signature is null

### ISSUE THREAD

**Issue by libsgh** [mengshouer/Cloud189Checkin#3]
我用go实现签到会报date/signature is null，header和你这个是一样的，cookie也是有效的，什么原因呢，python的就没问题
`<?xml version="1.0" encoding="UTF-8"?>
<error>
   <code>InvalidArgument</code>
   <message>date/signature is null</message>
</error>
`

**Comment by libsgh** [comment]
而且抽奖是可以的，就是签到不行
https://api.cloud.189.cn/mkt/userSign.action?rand={rand}&clientType=TELEANDROID&version=8.6.3&model=SM-G930K

**Comment by mengshouer** [comment]
信息太少看不出来，也没学过go，而且我也一个多月没管过这东西了(失忆
